// get all the clubs
GET http://localhost:3000/api/clubs

###

// registers a club; timestamp is added during insertion
// the authenticated admin must not already belong to a club
// after insertion, the new club id is assigned to the admin and returned by the API
POST http://localhost:3000/api/clubs
Content-Type: application/json
Authorization: Bearer <token>

{
    "name": "Biking Club",
    "address_line1": "Musterstraße 12",
    "postal_code": "79183",
    "city": "Waldkirch",
    "country": "Deutschland",
    "plan_type": "basic",
    "courts_count": 5,
    "start_hour": 9,
    "end_hour": 21,
    "timezone": "Europe/Berlin",
    "reservations_limit": 3
}

###

// update active/inactive courts for an existing club
POST http://localhost:3000/api/clubs
Content-Type: application/json
Authorization: Bearer <token>

{
    "_id": "686f544e85081abe19f78156",
    "update_type": "courts",
    "courts": ["court_1", "court_2", "court_4"]
}
