// get all reservations
GET http://localhost:3000/api/reservations?club_id=67a501832225683fb61ca069

###

// make a reservation in tsv
POST http://localhost:3000/api/reservations
Content-Type: application/json
Authorization: Bearer [add token here...]

{
  "club_id": "67a501832225683fb61ca069",
  "user_id": "679e1a839a82bd9b19fbb036",
  "court_num": "2",
  "date": "2025-05-09",
  "start_time": "15",
  "end_time": "18",
  "label": "api"
}

###

// make a reservation in waldkirch
POST http://localhost:3000/api/reservations
Content-Type: application/json
Authorization: Bearer [add token here...]

{
  "club_id": "67a6f9b2d791062c2d656097",
  "user_id": "67a66252c580d74db727bb43",
  "court_num": "3",
  "date": "2025-03-17",
  "start_time": "14",
  "end_time": "15"
}

###

// delete a reservation
DELETE http://localhost:3000/api/reservations?reservation_id=67d852d2ad76ec6b8cb5fe01
Content-Type: application/json
Authorization: Bearer [add token here...]

