// get all users of a club
GET http://localhost:3000/api/users?club_id=686f544e85081abe19f78156

###

// get a specific user by his id
GET http://localhost:3000/api/users?id=6901c515e273031e29ad9619

###

// update user
POST http://localhost:3000/api/users
Content-Type: application/json  
Authorization: Bearer <token>

{
    "user_id": "6901c515e273031e29ad9619",
    "status": "active"
}